### PR TITLE
Fix container initialization

### PR DESCRIPTION
**Pull request by zBritva**

### CODE REVIEW

**Review by danmarshall — CHANGES_REQUESTED** [review]
Should we use `requestAnimationFrame` instead of `setTimeout`?

**Comment by zBritva** [comment]
> Should we use `requestAnimationFrame` instead of `setTimeout`?

I don't think so, there is no rendering of animation.  We need to rework this method, because component state depends on props values.

**Review by danmarshall — APPROVED** [review]

**Comment by danmarshall** [comment]
Do you want to rework it, or merge to master?

**Comment by zBritva** [comment]
@danmarshall no, it will take time for refactoring. Let's merge if no any issues

**Pull request merged**
